-- Create Update User Data Stored Procedures
create or replace PROCEDURE PRO_UPDATE_CUSTOMER_DATA
(  
email_ in PRO_CUSTOMER.EMAIL% TYPE ,
FName in PRO_CUSTOMER.FIRST_NAME% TYPE, 
LName in PRO_CUSTOMER.LAST_NAME% TYPE, 
ADDRESS_  in PRO_CUSTOMER.ADDRESS% TYPE,
PASS_NUM  in PRO_CUSTOMER.PASSPORT_NUM% TYPE ,
CreditNum  in PRO_CUSTOMER.CREDIT_NUM% TYPE 

)
AS
BEGIN

update PRO_CUSTOMER set FIRST_NAME = FName , LAST_NAME = LName, address= ADDRESS_ , passport_num=PASS_NUM , credit_num=CreditNum
WHERE email = email_ ;

end PRO_UPDATE_CUSTOMER_DATA;
